load_col:
  inter: [user_id, item_id]
'USER_ID_FIELD': 'user_id'
'ITEM_ID_FIELD': 'item_id'

user_inter_num_interval: "[0,inf)"
item_inter_num_interval: "[0,inf)"

reg_weight: 1e-4
ssl_temp: 0.1
ssl_reg: 1e-9
alpha: 1
proto_reg: 1e-10
<<<<<<< HEAD
num_clusters: 100
=======
num_clusters: 500
batch_size: 54
>>>>>>> 8a1a1e4860d2af7160e94916debe20d4caa853da
